import "./globals.css";

import SmoothScrolling from "./components/SmoothScrolling";

export const metadata = {
  title: "Create Next App2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
       <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
